QoboLtd/project-template-wordpress

- composer.lock
> Upgrade project-template to v1.0.6

- composer.json
- composer.lock
* Updated wpcli to 0.18 from 0.17
* Added qobo-wp-shortcodes 1.0.0
> Composer Update

- .env.example
- composer.lock
Updated project-template to v1.0.9
> Project template update

- .env.example
- etc/wp-cli.install
- etc/wp-cli.update
**Would have been better if there is a check for already installed plugins**
> Fix already installed plugins

- composer.json
- composer.lock
Related to: https://codex.wordpress.org/Version_4.3
> Update WP to 4.3

- composer.json
Documentation: https://wordpress.org/plugins/listo/, http://contactform7.com/listo/
> Added listo plugin

- composer.json
- composer.lock
There where issues when using http so I switched to https as the latest documentation usage suggests 
https://github.com/outlandishideas/wpackagist
> Updated wpackagist url to https

- composer.json
- composer.lock
* Switched to [johnpbloch/wordpres](https://github.com/johnpbloch/wordpress/)
* Pushed all Qobo plugins to Packagist
> Composer simplifications

- .env.example
- bitbucket-pipelines.yml
- etc/nginx.conf.template
- etc/nginx.ssl.conf.template
- webroot/robots.php
- webroot/robots.txt
Merged [project-template v5.0.0](https://github.com/QoboLtd/project-template/releases/tag/v5.0.0)
> Merged project-template v5.0.0

- .env.example
- webroot/robots.php
Merged [project-template v5.1.0](https://github.com/QoboLtd/project-template/releases/tag/v5.1.0)
> Merged project-template v5.1.0

- README.md
- webroot/robots.php
Merged [project-template v5.1.2](https://github.com/QoboLtd/project-template/releases/tag/v5.1.2).
> Merged project-template v5.1.2

- webroot/custom-themes/custom/functions.php
- webroot/custom-themes/custom/lib/functions/debug.php
- webroot/custom-themes/custom/lib/functions/require-login.php
* Removed deprecated `@subpackage` tag
* Separated require-login function
* Added `debug()` function, similar to CakePHP
* Fixed CS issues.
> Minor fixes

- .editorconfig
- .travis.yml
- bitbucket-pipelines.yml
- phpcs.xml.dist
- phpunit.xml.dist
- tests/Unit/ComposerTest.php
- tests/Unit/DotenvTest.php
- tests/Unit/FaviconTest.php
- tests/Unit/RobotsTest.php
- webroot/robots.php
Merged [project-template v5.3.2](https://github.com/QoboLtd/project-template/releases/tag/v5.3.2) which brings a variety of improvements for PHPUnit and CodeSniffer configuration.
> Quality Assurance

- composer.json
* Updated Qobo-WP-Generic-Theme to [v1.1.2](https://github.com/QoboLtd/Qobo-WP-Generic-Theme/releases/tag/v1.1.2).
* Updated Qobo-Custom-Theme-Path to [v2.0.1](https://github.com/QoboLtd/Qobo-WP-Custom-Theme-Path/releases/tag/v2.0.1).
* Fixed indentation of `composer.json` as per `.editorconfig`.
> Minor updates and fixes

- composer.json
Updated WordPress and plugins to the latest versions.
> Wordpress update (task #3296)

- composer.json
- etc/wp-cli.install
- etc/wp-cli.update
* Removed Qobo Custom Theme Path plugin
* Added symlink to custom theme from WordPress theme folder in
both `wp-cli.install` and `wp-cli.update` scripts
> Fixed loading of custom theme (task #3358)

- bitbucket-pipelines.yml
- composer.json
* Merged project-template v5.4.2
* Updated WordPress to v4.7.3
> Merged project-template v5.4.2

- composer.json
Added bootstrap-for-contact-form-7 v1.4.2
Added multiple-post-thumbnails v1.6.6
> New plugins added

- webroot/custom-themes/custom/lib/functions/enqueue-parent-theme-style.php
Added bootstrap-extension.css that was lost after updating to project-template-wordpress v4.0.0
> Added bootstrap-extension.css

- .travis.yml
- README.md
Merged with [project-template v5.5.0](https://github.com/QoboLtd/project-template/releases/tag/v5.5.0).
> Merged with project-template v5.5.0

- composer.json
Changelogs summary:
- pyrech/composer-changelogs installed in version v1.5.1
Release notes: https://github.com/pyrech/composer-changelogs/releases/tag/v1.5.1
- johnpbloch/wordpress-core installed in version 4.8.0
Release notes: https://github.com/johnpbloch/wordpress-core/releases/tag/4.8.0
- wp-cli/php-cli-tools installed in version v0.11.3
Release notes: https://github.com/wp-cli/php-cli-tools/releases/tag/v0.11.3
- symfony/yaml installed in version v2.8.22
Release notes: https://github.com/symfony/yaml/releases/tag/v2.8.22
- symfony/polyfill-mbstring installed in version v1.4.0
Release notes: https://github.com/symfony/polyfill-mbstring/releases/tag/v1.4.0
- symfony/translation installed in version v2.8.22
Release notes: https://github.com/symfony/translation/releases/tag/v2.8.22
- …
> Update plugin disable-wordpress-updates

- etc/wp-cli.content
- etc/wp-cli.install
- etc/wp-cli.update
* Added more output for easier tracing
* Added transient cleanup at the end of install and update
> WP-CLI improvements

- composer.json
Added AMP plugin to composer.json
> Implement AMP support (task #5391)

- composer.json
wpackagist-plugin/multiple-post-thumbnails": "1.6.6" does not exist
> Fixed package version

- .travis.yml
- bitbucket-pipelines.yml
- docker-compose.yml
Updated to [project-template v9.1.0](https://github.com/QoboLtd/project-template/releases/tag/v9.1.0).
> Merged project-template v9.1.0

- composer.json
Updated to [project-template v9.2.0](https://github.com/QoboLtd/project-template/releases/tag/v9.2.0).
> Merged project-template v9.2.0

- docker-compose.yml
Updated to [project-template v9.2.1](https://github.com/QoboLtd/project-template/releases/tag/v9.2.1).
> Merged project-template v9.2.1

- .gitattributes
- README.md
- build/Robo/Command/App/App.php
Updated to [project-template v9.6.2](https://github.com/QoboLtd/project-template/releases/tag/v9.6.2).
> Merged project-template v9.6.2

- bitbucket-pipelines.yml
Updated to [project-template v9.7.0](https://github.com/QoboLtd/project-template/releases/tag/v9.7.0).
> Merged project-template v9.7.0

- .gitattributes
- .gitignore
- tests/Unit/DotenvTest.php
- webroot/robots.php
Updated to [project-template v10.1.1](https://github.com/QoboLtd/project-template/releases/tag/v10.1.1).
> Merged project-template v10.1.1

- .stickler.yml
- phpcs.xml.dist
* Updated to [project-template v10.2.1](https://github.com/QoboLtd/project-template/releases/tag/v10.2.1).
> Merged project-template v10.2.1

- composer.json
Replaced version constraint with exact number. (task #9608)
> Replaced constraint (task #9608)

- bitbucket-pipelines.yml
Merged project-template v10.5.2
> Merged project-template v10.5.2

- webroot/wp-config.php
Added a logic to check when its been executing from cli to avoid issues during app:install
> Changed the logic for the redirect ( Task #13802 )

- etc/wp-cli.update
Removed the part to update the category term with id=1 on every app update
> Removed the update category term during app update (Task #16329)
